### ISSUE TITLE
Support GAP8 GAPUINO board

### ISSUE THREAD

**Issue by ivankravets** [platformio/platform-riscv#1]
* https://greenwaves-technologies.com/en/developer-kits/gap8-developer-boards/

/cc @GreenWaves-Technologies, @Yaooooo, @owenchj

**Comment by Yaooooo** [comment]
Hi Ivan,
I am Yao ZHANG from GreenWaves Technologies. How can I help you?
Yao

**Comment by ivankravets** [comment]
1) Do you use the latest mbed-os core?
2) Are you familiar with https://scons.org/ ?

We can help you with integration for this board to PlatformIO. Please mail contact@pioplus.com.

**Comment by owenchj** [comment]
Yes, we use the latest mbed-os cores and we update with mbed master branch every  two weeks.

**Comment by diliplilaramani** [comment]
Hi @Yaooooo , can you tell me which LCD  screen this GAP8 Gapuino board supports as shown in this [video](https://youtu.be/KN9mOmHrM7M?t=20)?

**Comment by ivankravets** [comment]
Support for GAPuino board is added in a separate dev/platform. Please use:

- https://platformio.org/platforms/riscv_gap
