### ISSUE TITLE
Detected unknown package 'toolchain-riscv'"

### ISSUE THREAD

**Issue by fisherman6v6** [platformio/platform-riscv#3]
I'm having this issue either using Visual Studio Code or Atom. I'm on Arch Linux.
Nothing similar seems to be found on Google.

PIO Core Call Error: "The next files/directories have been created in /home/alessandro/Documents/Risc-V/Lab1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Detected unknown package 'toolchain-riscv'"

**Comment by ivankravets** [comment]
We don't have toolchain for i686. What is your architecture? See https://bintray.com/beta/#/platformio/dl-packages/tool-openocd-riscv/2.1000.20181218?tab=files

**Comment by fisherman6v6** [comment]
Thank you for your answer first of all.
My architecture is 64 bits so it isn't a i686 architecture.
How could the files that you link me solve this problem?

**Comment by ivankravets** [comment]
Do you use the latest version of dev/platform? Please open PlatformIO IDE > PIO Home > Platforms > Updates. Restart VSCode.

**Comment by ladecadence** [comment]
Same problem here, lastest platformio:  

```
% pio upgrade
You're up-to-date!
PlatformIO 3.6.5 is currently the newest version available.
```
All updated:  

```
% pio update 

Platform Manager
================
Platform RISC-V
--------
Updating riscv                           @ 0.3.0          [Up-to-date]
Updating framework-freedom-e-sdk         @ 1.20181009.0   [Up-to-date]
```
And the same problem:  

```
% pio run  
Processing freedom-e300-hifive1 (platform: riscv; board: freedom-e300-hifive1; framework: freedom-e-sdk)
------------------------------------------------------------------------------------------------------------------------
PackageManager: Installing toolchain-riscv @ ~1.70200.0
Error: Detected unknown package 'toolchain-riscv'
```
System is Debian Linux x64.

**Comment by ivankravets** [comment]
Sorry guys, this is an issue with our CDN. Let us fix ASAP.

**Comment by ivankravets** [comment]
Please try again, should work now.
