### ISSUE TITLE
Error compiling Blink for freedom-e300-hifive1

### ISSUE THREAD

**Issue by orende** [platformio/platform-riscv#4]
I've been trying to compile the standard Arduino Blink project for my Hifive1, but I'm running into compilation errors:

> ../bin/platformio run
Processing freedom-e300-hifive1 (platform: riscv; board: freedom-e300-hifive1; framework: freedom-e-sdk)
Verbose mode can be enabled via '-v, --verbose' option
CONFIGURATION: https://docs.platformio.org/page/boards/riscv/freedom-e300-hifive1.html
PLATFORM: RISC-V > HiFive1
HARDWARE: FE310 320MHz 16KB RAM (16MB Flash)
DEBUG: CURRENT(ftdi) ON-BOARD(ftdi)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 0 compatible libraries
Scanning dependencies...
No dependencies
Compiling .pioenvs/freedom-e300-hifive1/src/main.o
src/main.cpp: In function 'void setup()':
src/main.cpp:4:11: error: 'LED_BUILTIN' was not declared in this scope
pinMode(LED_BUILTIN, OUTPUT);
^~~~~~~~~~~
src/main.cpp:4:24: error: 'OUTPUT' was not declared in this scope
pinMode(LED_BUILTIN, OUTPUT);
^~~~~~
src/main.cpp:4:3: error: 'pinMode' was not declared in this scope
pinMode(LED_BUILTIN, OUTPUT);
^~~~~~~
src/main.cpp: In function 'void loop()':
src/main.cpp:9:16: error: 'LED_BUILTIN' was not declared in this scope
digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
^~~~~~~~~~~
src/main.cpp:9:29: error: 'HIGH' was not declared in this scope
digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
^~~~
src/main.cpp:9:3: error: 'digitalWrite' was not declared in this scope
digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
^~~~~~~~~~~~
src/main.cpp:10:3: error: 'delay' was not declared in this scope
delay(1000);                       // wait for a second
^~~~~
src/main.cpp:11:29: error: 'LOW' was not declared in this scope
digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
^~~
Compiling .pioenvs/freedom-e300-hifive1/sdk-libwrap/sys/close.o
Compiling .pioenvs/freedom-e300-hifive1/sdk-libwrap/sys/execve.o
*** [.pioenvs/freedom-e300-hifive1/src/main.o] Error 1
Compiling .pioenvs/freedom-e300-hifive1/sdk-libwrap/sys/fork.o
====================================== [ERROR] Took 0.45 seconds ======================================

This is my platform.ini:
>[env:freedom-e300-hifive1]
platform = riscv
board = freedom-e300-hifive1
framework = freedom-e-sdk

Riscv platform version: 0.3.0

pio update output:
> Platform RISC-V
Updating riscv                           @ 0.3.0          [Up-to-date]
Updating framework-freedom-e-sdk         @ 1.20181009.0   [Up-to-date]
Updating toolchain-riscv                 @ 1.70200.0      [Up-to-date]

The Blink code that I used:

```
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
```

I should mention that I've tried compiling with `#include "Arduino.h"` added to the includes section of the code, but got an 'Arduino.h not found" error.

**Comment by ivankravets** [comment]
There is no implementation for Arduino framework
